services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    ports:
        - "54320:5432"
    environment:
      - POSTGRES_PASSWORD=password-docker-compose
      - POSTGRES_DB:postgres
    volumes:
      - postres_data:/var/lib/postgresql/data 
volumes:
  postres_data:

